[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run build && npm run start:api"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "api"

[services.variables]
NODE_ENV = "production"
